version: "3"
service:
  db: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: olheoleo
      MYSQL_USER: admin
      MYSQL_PASSWORD: '123456'
    volume: ./init:/docker-entrypoint-initdb.d
  
  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080