package Main_Environment;


import java.util.ArrayList;

public class Tela_Listar_Produto extends javax.swing.JFrame {

    private String Email_Usuario_Logado;
    private ArrayList<Tipo_Produto> bd_tipo_produtos;
    public int cont = 0;

    public Tela_Listar_Produto() {
        initComponents();
    }

    public Tela_Listar_Produto(String Email_Usuario_Logado) {
        initComponents();
        this.Email_Usuario_Logado = Email_Usuario_Logado;

        try {
            Conexao con = new Conexao();
            this.bd_tipo_produtos = con.listProduct();
            DetailsUpdate();
            
        } catch (Exception e) {
            System.out.println(e.getCause());
        }
    }

    public void DetailsUpdate() {
        //Colocar os valores iniciais no campos de produto_nome, produto_marca, produto_preco, produto_descricao
        this.Nome_Label.setText(bd_tipo_produtos.get(cont).getNome_Produto());
        this.Marca_Label.setText(bd_tipo_produtos.get(cont).getMarca_Produto());
        this.Preco_Label.setText(Float.toString(bd_tipo_produtos.get(cont).getPreco_Produto()));
        this.Descricao_Label.setText(bd_tipo_produtos.get(cont).getDescricao_Produto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IrCarros_Button = new javax.swing.JButton();
        Prox_Prod_Button = new javax.swing.JButton();
        Ante_Prod_Button = new javax.swing.JButton();
        Criar_Prod_Button = new javax.swing.JButton();
        Nome_Label = new javax.swing.JLabel();
        Marca_Label = new javax.swing.JLabel();
        Preco_Label = new javax.swing.JLabel();
        Descricao_Label = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IrCarros_Button.setBorderPainted(false);
        IrCarros_Button.setContentAreaFilled(false);
        IrCarros_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IrCarros_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrCarros_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(IrCarros_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 60, 60));

        Prox_Prod_Button.setBorderPainted(false);
        Prox_Prod_Button.setContentAreaFilled(false);
        Prox_Prod_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Prox_Prod_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prox_Prod_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Prox_Prod_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 313, 40, 40));

        Ante_Prod_Button.setBorderPainted(false);
        Ante_Prod_Button.setContentAreaFilled(false);
        Ante_Prod_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ante_Prod_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ante_Prod_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Ante_Prod_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 50, 40));

        Criar_Prod_Button.setBorderPainted(false);
        Criar_Prod_Button.setContentAreaFilled(false);
        Criar_Prod_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Criar_Prod_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Criar_Prod_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Criar_Prod_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 563, 70, 70));

        Nome_Label.setText("Nome do Produto");
        getContentPane().add(Nome_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 160, 20));

        Marca_Label.setText("Marca do Produto");
        getContentPane().add(Marca_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 170, 20));

        Preco_Label.setText("Preco do Produto");
        getContentPane().add(Preco_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 160, 20));

        Descricao_Label.setText("Descrição do Produto");
        getContentPane().add(Descricao_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 160, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/Tela_Produtos.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IrCarros_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrCarros_ButtonActionPerformed
        this.setVisible(false);
        Tela_Listar_Carros t_l_c = new Tela_Listar_Carros(Email_Usuario_Logado);
        t_l_c.setVisible(true);
    }//GEN-LAST:event_IrCarros_ButtonActionPerformed

    private void Criar_Prod_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Criar_Prod_ButtonActionPerformed
        this.setVisible(false);
        Tela_Criar_Produto t_c_p = new Tela_Criar_Produto(Email_Usuario_Logado);
        t_c_p.setVisible(true);
    }//GEN-LAST:event_Criar_Prod_ButtonActionPerformed

    private void Prox_Prod_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prox_Prod_ButtonActionPerformed
        cont++;
        if (cont > bd_tipo_produtos.size() - 1) {
            cont = 0;
        }
        DetailsUpdate();
    }//GEN-LAST:event_Prox_Prod_ButtonActionPerformed

    private void Ante_Prod_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ante_Prod_ButtonActionPerformed
        cont--;
        if (cont < 0) {
            cont = bd_tipo_produtos.size() - 1;
        }
        DetailsUpdate();
    }//GEN-LAST:event_Ante_Prod_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Listar_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Listar_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Listar_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Listar_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Listar_Produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ante_Prod_Button;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Criar_Prod_Button;
    private javax.swing.JLabel Descricao_Label;
    private javax.swing.JButton IrCarros_Button;
    private javax.swing.JLabel Marca_Label;
    private javax.swing.JLabel Nome_Label;
    private javax.swing.JLabel Preco_Label;
    private javax.swing.JButton Prox_Prod_Button;
    // End of variables declaration//GEN-END:variables
}
