/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author cg3023087
 */
public class Tela_Cadastro_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Cadastro_Usuario
     */
    public Tela_Cadastro_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Photo_Alter = new javax.swing.JButton();
        Continue_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Name_Field = new javax.swing.JTextField();
        Email_Field = new javax.swing.JTextField();
        Password_Field = new javax.swing.JPasswordField();
        Confirm_Password_Field = new javax.swing.JPasswordField();
        Tela_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(370, 844));
        setSize(new java.awt.Dimension(375, 844));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Photo_Alter.setContentAreaFilled(false);
        Photo_Alter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Photo_Alter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 170, 40));

        Continue_Button.setContentAreaFilled(false);
        Continue_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Continue_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Continue_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Continue_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 740, 180, 50));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, 130));

        Name_Field.setBackground(new java.awt.Color(245, 245, 245));
        Name_Field.setForeground(new java.awt.Color(0, 0, 0));
        Name_Field.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(Name_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 355, 280, 30));

        Email_Field.setBackground(new java.awt.Color(245, 245, 245));
        Email_Field.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(Email_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 456, 280, 30));

        Password_Field.setBackground(new java.awt.Color(245, 245, 245));
        Password_Field.setForeground(new java.awt.Color(0, 0, 0));
        Password_Field.setText("jPasswordField1");
        Password_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_FieldActionPerformed(evt);
            }
        });
        getContentPane().add(Password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 280, -1));

        Confirm_Password_Field.setBackground(new java.awt.Color(245, 245, 245));
        Confirm_Password_Field.setForeground(new java.awt.Color(0, 0, 0));
        Confirm_Password_Field.setText("jPasswordField1");
        getContentPane().add(Confirm_Password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 280, -1));

        Tela_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/Tela_Cadastro_Usuario.png"))); // NOI18N
        getContentPane().add(Tela_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 820));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Continue_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Continue_ButtonActionPerformed
        Tela_Criar_Automovel t_c_a = new Tela_Criar_Automovel();
        t_c_a.setVisible(true);
    }//GEN-LAST:event_Continue_ButtonActionPerformed

    private void Password_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastro_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Confirm_Password_Field;
    private javax.swing.JButton Continue_Button;
    private javax.swing.JTextField Email_Field;
    private javax.swing.JTextField Name_Field;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JButton Photo_Alter;
    private javax.swing.JLabel Tela_Background;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
